#
#
AC_INIT([ClipboardViewerQT],[0.1.0],[PROJ],[ClipboardViewerQT])

AC_CONFIG_HEADERS([config.h])
AC_PROG_CXX

AM_INIT_AUTOMAKE

AC_PROG_CC
AC_PROG_CXX

QTWIDGETS_MODULES="Qt6Widgets >= 6.6.0"
PKG_CHECK_MODULES(QTWIDGETS, $QTWIDGETS_MODULES)
AC_SUBST(QTWIDGETS_CFLAGS)
AC_SUBST(QTWIDGETS_LIBS)

QTCORE_MODULES="Qt6Core >= 6.6.0"
PKG_CHECK_MODULES(QTCORE, $QTCORE_MODULES)
AC_SUBST(QTCORE_CFLAGS)
AC_SUBST(QTCORE_LIBS)

AC_CONFIG_FILES(Makefile ClipboardViewerQT/app/Makefile)
AC_OUTPUT

