.\" clipboardviewerqt
.TH "clipboardviewerqt" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
clipboardviewerqt \- manual page for clipboardviewerqt 0.0.0
.SH "SYNOPSIS"
.B clipboardviewerqt
.SH "DESCRIPTION"
A GUI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
clipboardviewerqt
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
